	AREA PRG,CODE,READONLY
	ENTRY
	
	LDR R0,=SOURCE_DATA
	LDR R1,=DESTINATION_DATA
	MOV R2,#5
	
TRANSFER_LOOP
	LDMIA R0!,{R3-R7}
	STMIA R1!,{R3-R7}
	SUBS R2,R2,#5
	BNE TRANSFER_LOOP
	
STOP
	B STOP
	AREA DATA,DATA,READWRITE
SOURCE_DATA
	DCD 10,20,30,40,50
DESTINATION_DATA
	DCD 0,0,0,0,0
	END
